### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by benji6** [mcanthony/OpenDAWN#1]
The readme sounds very exciting, but there's nothing else here...

**Comment by jarmitage** [comment]
also interested...

**Comment by GregoryCollett** [comment]
I am also interested...

On that note, anyone willing to collaborate on a browser based DAW? This project seems to have been inactive for a while now.

**Comment by benji6** [comment]
I have been working on a declarative web audio library [here](https://github.com/benji6/virtual-audio-graph) and the very beginnings of something that could one day be a DAW [here](https://github.com/benji6/elemental). I am very open to collaborating on a browser-based DAW.

**Comment by 1j01** [comment]
I'm also working an [audio editor](https://github.com/1j01/audio-editor) and wondering what this is.
Does SMP refer to Symmetric Multiprocessing? ~~Software Management Plan?~~

**Comment by jonpatterns** [comment]
me too : -)
